/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BInputGroupPrepend: typeof import('bootstrap-vue-next')['BInputGroupPrepend']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    BTooltip: typeof import('bootstrap-vue-next')['BTooltip']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
