# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v3

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build Murmur library
        run: yarn build

      - name: Build storybook artifacts
        run: yarn build-storybook

      # Upload storybook to repository's artifacts
      - name: Upload storybook artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - uses: actions/deploy-pages@v4


